// ignore: depend_on_referenced_packages
//import 'package:uuid/uuid.dart';

//var uuid = const Uuid();
/*
The song model should take user input for album,
artist, release date, etc. Some of the data should be 
optional so not to annoy the user.
*/


class Song{
  //final String uuid;
  final int? id;
  final String link;
  Song({this.id,required this.link});
  factory Song.fromMap(Map<String,dynamic> json) => Song(
    id: json["id"],
    link: json["link"],
    );
/*ID shouldn't be assigned by a user, it should be autogenerated. 
Best would be to keep date and uuid(Both autogenerated) automatically generated 
and the songs to be sorted by date*/
    Map<String,dynamic> toMap(){
      return{
        'id':id,
        'link':link,
      };
    } 
}